### ISSUE TITLE
Cannot sell/buy item when playing online/ladder

### ISSUE THREAD

**Issue by baolhq** [Warren1001/ighe#3]
As the title suggests, I'm unable to play online now, if I try to play the game without additional command line arguments it crash immediately on launch.
Tried reinstalling the game, scan and repair, delete mods folder, nothing work.
How can I fix this?

**Comment by Warren1001** [comment]
your title and your description are different.. you can't buy/sell stuff because you're running a mod of the game. disable the mod. see below for disabling the mod without crashing.
i wrote that your game would crash if you tried to load a character using the hacked small charm without the mod. you need to load the mod, load the characterw ith the hacked charm, drop the charm, and then you can load it with the original game.

"The purpose of the charm is for rushing/quest completing. You must toss it on the ground if you plan to use the character outside of the mod. If you try to load a character that has the charm with the unmodded game or another mod, the game will crash on load (or it just won't let you load that character, don't remember which happens). You will hit level 99 by the time you finish Hell using the rushing method."

d2r loads all the singleplayer characters when it loads. "load" here doesn't mean selecting the character, just means launching the game.
